### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by sqpp** [hlf20010508/Vue3-Socket.io#1]
Hey, nice one!

Are you planning to add Typescript support/types?

**Comment by hlf20010508** [comment]
Well I don't use typescript.
I need other people's PRs.

**Comment by sqpp** [comment]
Got it, thank you either way!

**Comment by hlf20010508** [comment]
Hey there.
I think I've implemented Typescript support, and rewritten the whole project in Typescript.
But before publishing it, can you help me test it in your project to see whether there's any problem?
I just learnt Typescript a little bit, I'm not sure if I was doing everything right.
It's in the `ts` branch.
